Alter table CUSTOMERS add (DNI varchar2(9));
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;

CREATE SEQUENCE ID_CUSTOMER
	INCREMENT BY 1
	START WITH 1;

CREATE TABLE PRODUCTS 
   (	IDPRODUCT NUMBER(*,0) NOT NULL,
	NAME VARCHAR2(60) NOT NULL,
	REFCOMPOSITION NUMBER(*,0) NOT NULL,
	REFSIZES NUMBER(*,0) NOT NULL, 
	PRICE FLOAT(126) NOT NULL, 
	AMOUNT NUMBER(*,0) NOT NULL,
	DELETED NUMBER(*,0) NOT NULL,
	CONSTRAINT PK_PRODUCTS PRIMARY KEY (IDPRODUCT)
   );


CREATE TABLE COMPOSITIONS(
    IDCOMPOSITION NUMBER(*,0) NOT NULL,
    COMPOSITION VARCHAR2(40 BYTE) NOT NULL,
	CONSTRAINT PK_COMPOSITIONS PRIMARY KEY (IDCOMPOSITION)
    );

	
CREATE TABLE SIZES(
	IDSIZE NUMBER(*,0) NOT NULL,
	SIZENAME VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_SIZES PRIMARY KEY (IDSIZE)
);


CREATE SEQUENCE IDCOMPOSITION
	INCREMENT BY 1
	START WITH 1;
	
CREATE SEQUENCE IDPRODUCT
	INCREMENT BY 1
	START WITH 1
	NOCACHE;

INSERT INTO CUSTOMERS VALUES (ID_CUSTOMER.NEXTVAL, 'Antonio','Sánchez', 'calle, 17',12345678,'antonio@gmail.com',0,2);

ALTER TABLE PRODUCTS ADD CONSTRAINT PROD_COMP_FK FOREIGN KEY (REFCOMPOSITION) REFERENCES COMPOSITIONS (IDCOMPOSITION);
ALTER TABLE PRODUCTS ADD CONSTRAINT PROD_SIZES_FK FOREIGN KEY (REFSIZES) REFERENCES SIZES(IDSIZE);

INSERT INTO SIZES VALUES (1,'XXS');
INSERT INTO SIZES VALUES (2,'XS');
INSERT INTO SIZES VALUES (3,'S');
INSERT INTO SIZES VALUES (4,'M');
INSERT INTO SIZES VALUES (5,'L');
INSERT INTO SIZES VALUES (6,'XL');
INSERT INTO SIZES VALUES (7,'XXL');

INSERT INTO COMPOSITIONS(IDCOMPOSITION, COMPOSITION) VALUES (IDCOMPOSITION.NEXTVAL, 'Algodon');
INSERT INTO COMPOSITIONS(IDCOMPOSITION, COMPOSITION) VALUES (IDCOMPOSITION.NEXTVAL, 'Latex');
INSERT INTO COMPOSITIONS(IDCOMPOSITION, COMPOSITION) VALUES (IDCOMPOSITION.NEXTVAL, 'Lana');
INSERT INTO COMPOSITIONS(IDCOMPOSITION, COMPOSITION) VALUES (IDCOMPOSITION.NEXTVAL, 'Seda');
INSERT INTO COMPOSITIONS(IDCOMPOSITION, COMPOSITION) VALUES (IDCOMPOSITION.NEXTVAL, 'Lino');
INSERT INTO COMPOSITIONS(IDCOMPOSITION, COMPOSITION) VALUES (IDCOMPOSITION.NEXTVAL, 'Cuero');
INSERT INTO COMPOSITIONS(IDCOMPOSITION, COMPOSITION) VALUES (IDCOMPOSITION.NEXTVAL, 'Poliester');

INSERT INTO PRODUCTS VALUES (IDPRODUCT.NEXTVAL,'Polo shirt',1,4,15.2,10,0);
INSERT INTO PRODUCTS VALUES (IDPRODUCT.NEXTVAL,'Shirt',2,6,10.7,30,0);

CREATE SEQUENCE SEQ_TAGS
	INCREMENT BY 1
	START WITH 1;

CREATE TABLE TAGS(
	IDTAG NUMBER(*,0) NOT NULL,
	NAME VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_TAGS PRIMARY KEY (IDTAG)
);


CREATE TABLE TAGS_CUSTOMERS(
	REFIDTAG NUMBER(*,0) NOT NULL,
	REFIDCUSTOMER NUMBER(*,0) NOT NULL,
	CONSTRAINT TAGS_ID_FK FOREIGN KEY (REFIDTAG) REFERENCES TAGS (IDTAG),
	CONSTRAINT TAGS_CUSTOMERS_FK FOREIGN KEY (REFIDCUSTOMER) REFERENCES CUSTOMERS (IDCUSTOMER)
);

CREATE TABLE TAGS_PRODUCTS(
	REFIDTAG NUMBER(*,0) NOT NULL,
	REFIDPRODUCT NUMBER(*,0) NOT NULL,
	CONSTRAINT TAGSPR_ID_FK FOREIGN KEY (REFIDTAG) REFERENCES TAGS (IDTAG),
	CONSTRAINT TAGSPR_CUSTOMERS_FK FOREIGN KEY (REFIDPRODUCT) REFERENCES PRODUCTS (IDPRODUCT)
);

commit;